apiVersion: v1
kind: ConfigMap
metadata:
  name: render-ingress-nginx-kustomization
  annotations:
    config.kubernetes.io/function: |
      container:
        image: docker.io/mgoltzsche/kustomizr:latest
        network: true
    config.kubernetes.io/local-config: 'true'
data:
  path: .
  outputPath: static/generated-manifest.yaml
  '--reorder': none
