apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: dev-hello-world
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - echo Hello $AUDIENCE; sleep infinite
        env:
        - name: AUDIENCE
          valueFrom:
            configMapKeyRef:
              key: audience
              name: dev-hello-config-h7872h2b6h
        image: alpine:3.12
        name: hello-world
---
apiVersion: v1
data:
  audience: world
kind: ConfigMap
metadata:
  labels:
    app: hello-world
  name: dev-hello-config-h7872h2b6h
  namespace: default
