name: Semantic release

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Log into DockerHub registry
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login docker.io -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Install semantic-release
      run: npm install semantic-release@17.4.2 @semantic-release/exec@5.0.0 @semantic-release/git@9.0.0

    - name: Release eventually
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        GIT_AUTHOR_NAME: "mgoltzsche"
        GIT_AUTHOR_EMAIL: "max.goltzsche@gmail.com"
        GIT_COMMITTER_NAME: "mgoltzsche"
        GIT_COMMITTER_EMAIL: "max.goltzsche@gmail.com"
      run: npx semantic-release

